import os, json

base = r'frontend\src\pages\solutions'
os.makedirs(base, exist_ok=True)

pages = {
'ITSolutions': {'title':'End-to-End IT Solutions','slug':'it-solutions','stype':'IT Solutions','tagline':'Enterprise IT Architecture','hero_title':'Engineering','hero_highlight':'Digital Excellence','hero_sub':'From bespoke software to robust infrastructure, we architect scalable IT systems that power modern enterprises.','hero_img':'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1920&auto=format&fit=crop','accent_from':'from-blue-600','accent_to':'to-cyan-500','accent_text':'text-blue-400','accent_bg':'bg-blue-600/20','accent_border':'border-blue-500/30','icons':['Server','Code','Cpu','ShieldCheck'],'services':[('Infrastructure Support','24/7 network monitoring, server management, and zero-downtime architecture.'),('Custom Software Dev','Full-stack enterprise applications tailored to your business logic.'),('Cloud Migration','Seamless AWS/Azure migration with data security and performance tuning.'),('IT Consulting','Strategic technology roadmap planning for startups and enterprises.')],'steps':[('Discovery','Requirements mapping and architecture blueprinting.'),('Prototype','UI/UX wireframes and feasibility validation.'),('Build','Agile sprints with CI/CD pipelines.'),('Launch','QA testing and zero-risk production deployment.')],'why':[('Proven Expertise','5+ years delivering IT transformation across 100+ clients.'),('Dedicated Team','Assigned developers and PMs for every project.'),('Agile Delivery','Weekly sprints and transparent progress reporting.')],'stats':[('200','Projects Delivered','+'),('100','Corporate Partners','+'),('5','Years Experience','+'),('24','Support Hours','x7')]},

'CustomSoftware': {'title':'Custom Software Development','slug':'custom-software-development','stype':'Custom Software Development','tagline':'Bespoke Digital Products','hero_title':'Software Built','hero_highlight':'For Your Business','hero_sub':'We engineer tailor-made software, SaaS platforms, and business automation tools from scratch.','hero_img':'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1920&auto=format&fit=crop','accent_from':'from-violet-600','accent_to':'to-purple-500','accent_text':'text-violet-400','accent_bg':'bg-violet-600/20','accent_border':'border-violet-500/30','icons':['Code','Layers','Settings','Zap'],'services':[('SaaS Development','Multi-tenant cloud platforms with subscription billing and analytics.'),('Enterprise Apps','Internal tools, dashboards, and workflow management systems.'),('API-First Architecture','Scalable REST/GraphQL APIs connecting your entire tech stack.'),('Legacy Modernization','Migrate outdated systems to modern, maintainable codebases.')],'steps':[('Requirement Analysis','Deep-dive into your business process and tech requirements.'),('System Design','Database schema, architecture, and API contracts.'),('Development','Iterative builds with weekly demos.'),('Deployment','Go-live assistance and long-term maintenance.')],'why':[('Domain Experts','Developers with specialization in your industry vertical.'),('IP Ownership','Full source code ownership transferred to you.'),('Scalable Codebase','Built to grow from 100 to 1 million users without rewrites.')],'stats':[('150','Apps Built','+'),('98','Client Satisfaction','%'),('12','Tech Stacks',''),('3','Month Avg Delivery','')]},

'WebApplication': {'title':'Web Application Development','slug':'web-application-development','stype':'Web Application Development','tagline':'High-Performance Web Apps','hero_title':'Web Apps That','hero_highlight':'Scale & Convert','hero_sub':'From business dashboards to SaaS portals, we build fast, secure, and responsive web applications that deliver results.','hero_img':'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1920&auto=format&fit=crop','accent_from':'from-sky-600','accent_to':'to-blue-500','accent_text':'text-sky-400','accent_bg':'bg-sky-600/20','accent_border':'border-sky-500/30','icons':['Globe','Layers','Zap','ShieldCheck'],'services':[('Progressive Web Apps','Offline-capable, app-like experiences delivered through the browser.'),('Admin Dashboards','Real-time analytics, CRUD interfaces, and role-based access control.'),('E-commerce Portals','Multi-vendor storefronts with payment gateway integration.'),('Business Portals','Customer-facing self-service platforms and workflow tools.')],'steps':[('UX Research','User journey mapping and competitor analysis.'),('Design System','Component library, brand alignment, and accessibility.'),('Engineering','React/Next.js frontend with Node.js backend.'),('Performance QA','Lighthouse audits, load testing, and SEO optimization.')],'why':[('SEO-Optimized','Every page scored 90+ on Google Lighthouse.'),('Mobile-First','Pixel-perfect on every device and screen size.'),('Security Built-In','HTTPS, CSRF protection, and regular vulnerability scans.')],'stats':[('120','Web Apps','+'),('90','Lighthouse Score','avg'),('99','Uptime','%'),('48','Hr Turnaround','')]},

'MobileApp': {'title':'Mobile App Development','slug':'mobile-app-development','stype':'Mobile App Development','tagline':'iOS & Android Solutions','hero_title':'Apps That Live','hero_highlight':'In Every Pocket','hero_sub':'Native and cross-platform mobile applications that engage users, drive retention, and scale with your business.','hero_img':'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1920&auto=format&fit=crop','accent_from':'from-emerald-600','accent_to':'to-teal-500','accent_text':'text-emerald-400','accent_bg':'bg-emerald-600/20','accent_border':'border-emerald-500/30','icons':['Smartphone','Zap','ShieldCheck','Star'],'services':[('React Native','Single codebase for iOS and Android with near-native performance.'),('Flutter Development','Beautiful, expressive UIs with smooth 60fps animations.'),('iOS Native','High-performance apps leveraging the full Apple ecosystem.'),('Android Native','Kotlin-based apps optimized for the Google Play ecosystem.')],'steps':[('App Strategy','Platform choice, tech stack, and monetization planning.'),('UI/UX Design','Wireframes, interactive prototypes, and design handoff.'),('Development','Sprint-based development with TestFlight/Play beta access.'),('App Store Launch','Submission, ASO optimization, and post-launch monitoring.')],'why':[('Cross-Platform Experts','Reduce cost without sacrificing quality with shared codebases.'),('App Store Track Record','50+ apps live on App Store and Google Play.'),('Ongoing Support','Monthly maintenance, OS update compatibility, and analytics.')],'stats':[('80','Apps Published','+'),('50','Play Store','+'),('4.8','Avg Rating','★'),('30','Day Delivery','')]},

'ERPSolutions': {'title':'ERP Solutions for Business','slug':'erp-solutions','stype':'ERP Solutions','tagline':'Enterprise Resource Planning','hero_title':'Unify Your','hero_highlight':'Entire Business','hero_sub':'Comprehensive ERP systems for schools, manufacturers, retailers, and enterprises. One platform, every module.','hero_img':'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1920&auto=format&fit=crop','accent_from':'from-orange-600','accent_to':'to-amber-500','accent_text':'text-orange-400','accent_bg':'bg-orange-600/20','accent_border':'border-orange-500/30','icons':['Layers','Database','Users','TrendingUp'],'services':[('Inventory Management','Real-time stock tracking, auto-reorder, and supplier management.'),('HRMS & Payroll','Employee lifecycle, attendance, payroll processing, and compliance.'),('Finance & Accounting','GL, AP/AR, budgeting, and automated financial reporting.'),('School ERP','Admissions, fee collection, timetable, and student progress tracking.')],'steps':[('Business Audit','Map existing workflows and identify automation opportunities.'),('Module Planning','Select and configure only the modules you need.'),('Data Migration','Safely transfer legacy data with validation.'),('Training & Go-Live','Staff training and post-deployment support.')],'why':[('Industry-Specific','ERP modules pre-configured for manufacturing, retail, education.'),('No Vendor Lock-In','Source code and full data ownership with your team.'),('ROI in 6 Months','Average 40% reduction in operational costs.')],'stats':[('60','ERP Deployments','+'),('40','Cost Reduction','%'),('12','Industries',''),('99','Data Accuracy','%')]},

'CRMSolutions': {'title':'CRM Solutions','slug':'crm-solutions','stype':'CRM Solutions','tagline':'Customer Relationship Management','hero_title':'Turn Leads Into','hero_highlight':'Loyal Customers','hero_sub':'Automated lead pipelines, smart follow-ups, and actionable sales analytics that accelerate revenue growth.','hero_img':'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1920&auto=format&fit=crop','accent_from':'from-rose-600','accent_to':'to-pink-500','accent_text':'text-rose-400','accent_bg':'bg-rose-600/20','accent_border':'border-rose-500/30','icons':['Users','TrendingUp','MessageSquare','Target'],'services':[('Lead Pipeline Automation','Capture, score, and nurture leads automatically from all channels.'),('Sales Dashboards','Real-time performance metrics, forecasts, and team leaderboards.'),('Customer 360 View','Unified customer history, interactions, and purchase timeline.'),('Email & WhatsApp Integration','Trigger personalized communication at every sales stage.')],'steps':[('Sales Process Mapping','Document your current funnel and identify conversion bottlenecks.'),('CRM Configuration','Custom fields, pipelines, and automation rules built for your team.'),('Data Import','Clean and migrate existing contacts, deals, and history.'),('Training & Adoption','Hands-on team training and workflow documentation.')],'why':[('3x Faster Follow-ups','Automated reminders eliminate lead leakage.'),('Custom Pipelines','Every business has a unique sales process.'),('Integration Ready','Connects with WhatsApp, email, payment gateways, and ERP.')],'stats':[('3','x Faster Follow-up',''),('45','Lead Conversion Boost','%'),('80','Clients','+ active'),('24','Setup Time','hrs')]},

'DigitalMarketing': {'title':'Digital Marketing Services','slug':'digital-marketing','stype':'Digital Marketing','tagline':'Performance Marketing','hero_title':'Marketing That','hero_highlight':'Drives Results','hero_sub':'Data-driven campaigns across Google, Meta, LinkedIn, and YouTube that deliver measurable ROI, not just impressions.','hero_img':'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=1920&auto=format&fit=crop','accent_from':'from-pink-600','accent_to':'to-fuchsia-500','accent_text':'text-pink-400','accent_bg':'bg-pink-600/20','accent_border':'border-pink-500/30','icons':['TrendingUp','Target','BarChart2','Zap'],'services':[('Google Ads','Search, display, and shopping campaigns with conversion-focused bidding.'),('Meta Ads','Facebook and Instagram campaigns targeting precise audience segments.'),('LinkedIn Marketing','B2B lead generation and brand positioning for decision-makers.'),('Performance Analytics','Real-time dashboards with ROAS, CAC, and LTV tracking.')],'steps':[('Audit & Strategy','Competitor analysis, audience profiling, and goal alignment.'),('Campaign Setup','Ad creative, targeting, and funnel architecture.'),('Launch & Optimize','A/B testing, bid management, and creative iteration.'),('Reporting','Weekly performance reports with actionable insights.')],'why':[('ROI-Focused','Every rupee tracked to measurable business outcomes.'),('Creative + Data','In-house designers and data scientists work together.'),('Transparent Reporting','Real-time dashboard access with no hidden metrics.')],'stats':[('3','Average ROAS','x'),('60','Brands Managed','+'),('30','Cost Per Lead Reduction','%'),('6','Years Experience','')]},

'SEO': {'title':'Search Engine Optimization','slug':'seo','stype':'SEO','tagline':'Organic Growth Engine','hero_title':'Rank Higher,','hero_highlight':'Grow Faster','hero_sub':'Technical, on-page, and local SEO strategies that drive sustainable organic traffic and qualified leads.','hero_img':'https://images.unsplash.com/photo-1572177812156-58036aae439c?q=80&w=1920&auto=format&fit=crop','accent_from':'from-green-600','accent_to':'to-emerald-500','accent_text':'text-green-400','accent_bg':'bg-green-600/20','accent_border':'border-green-500/30','icons':['Search','TrendingUp','FileText','Globe'],'services':[('Technical SEO','Site speed, Core Web Vitals, crawlability, and structured data.'),('On-Page Optimization','Keyword research, meta optimization, and content structuring.'),('Local SEO','Google Business Profile, map pack ranking, and citation building.'),('Content Strategy','SEO-driven content calendar, blog writing, and topical authority building.')],'steps':[('SEO Audit','Full technical analysis and competitor gap mapping.'),('Keyword Research','High-intent keyword discovery and content opportunity mapping.'),('On-Page & Technical Fixes','Implementing all optimizations in priority order.'),('Link Building & Content','Authority building through quality backlinks and fresh content.')],'why':[('Sustainable Traffic','Rankings built on white-hat practices that last years.'),('Transparent Reporting','Monthly keyword ranking, traffic, and conversion reports.'),('Content Expertise','In-house writers producing search-optimized content.')],'stats':[('120','#1 Rankings',''),('5','Avg Traffic Growth','x'),('6','Month Timeline','mo'),('40','Active Clients','')]},

'Branding': {'title':'Brand Identity & Strategy','slug':'branding','stype':'Branding','tagline':'Brand Identity Experts','hero_title':'Build a Brand','hero_highlight':'That Stands Out','hero_sub':'From logo design to full brand systems, we craft memorable identities that resonate with your audience and outlast trends.','hero_img':'https://images.unsplash.com/photo-1542744094-3a31f272c490?q=80&w=1920&auto=format&fit=crop','accent_from':'from-yellow-500','accent_to':'to-orange-500','accent_text':'text-yellow-400','accent_bg':'bg-yellow-500/20','accent_border':'border-yellow-500/30','icons':['Layers','Star','Award','Zap'],'services':[('Logo Design','Strategic, memorable logos that communicate your brand values instantly.'),('Visual Identity System','Typography, color palette, iconography, and usage guidelines.'),('Brand Strategy','Positioning, messaging framework, tone of voice, and target persona.'),('Marketing Collateral','Business cards, pitch decks, brochures, and social media kits.')],'steps':[('Brand Discovery','Workshops to uncover your vision, values, and target audience.'),('Concept Development','Multiple creative directions presented for feedback.'),('Design Refinement','Iteration on selected direction until perfect.'),('Brand Delivery','Final files in all formats with comprehensive brand guide.')],'why':[('Strategy-Led Design','Every visual decision backed by market and audience research.'),('100% Original','No templates, stock logos, or AI-generated shortcuts.'),('Unlimited Revisions','We refine until you love it.')],'stats':[('200','Brands Created','+'),('15','Industries',''),('100','Client Approval','%'),('7','Day Delivery','')]},

'SocialMedia': {'title':'Social Media Marketing','slug':'social-media-marketing','stype':'Social Media Marketing','tagline':'Social Media Experts','hero_title':'Content That','hero_highlight':'Builds Community','hero_sub':'Creative content strategies, stunning visuals, and data-driven campaigns that grow your audience and drive engagement.','hero_img':'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=1920&auto=format&fit=crop','accent_from':'from-fuchsia-600','accent_to':'to-violet-500','accent_text':'text-fuchsia-400','accent_bg':'bg-fuchsia-600/20','accent_border':'border-fuchsia-500/30','icons':['Globe','Share2','TrendingUp','Zap'],'services':[('Content Calendar','30-day planned content strategy with captions, hashtags, and design.'),('Reel & Video Production','Short-form video content optimized for Instagram and YouTube Shorts.'),('Community Management','Daily engagement, comment responses, and DM handling.'),('Influencer Coordination','Micro and macro influencer identification and campaign management.')],'steps':[('Social Audit','Review existing presence and competitor benchmarking.'),('Strategy Development','Platform-specific content pillars and posting frequency.'),('Content Production','Design, copywriting, and scheduling of all posts.'),('Monitor & Grow','Monthly reporting on reach, engagement, and follower growth.')],'why':[('Platform Specialists','Dedicated experts for each platform.'),('Original Creative','In-house designers producing scroll-stopping content.'),('Proven Engagement','Average 3-5x engagement boost within 3 months.')],'stats':[('50','Brands Managed','+'),('3','Avg Engagement Boost','x'),('2M','Monthly Impressions','+'),('7','Day Content Refresh','')]},

'Recruitment': {'title':'Corporate & IT Recruitment','slug':'recruitment','stype':'Recruitment','tagline':'Talent Acquisition Experts','hero_title':'Hire the','hero_highlight':'Right Talent','hero_sub':'End-to-end recruitment across IT, banking, FMCG, and manufacturing. Source, screen, and deliver ready-to-contribute candidates.','hero_img':'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1920&auto=format&fit=crop','accent_from':'from-blue-600','accent_to':'to-indigo-500','accent_text':'text-blue-400','accent_bg':'bg-blue-600/20','accent_border':'border-blue-500/30','icons':['Users','Briefcase','CheckCircle2','Award'],'services':[('IT Recruitment','Software engineers, DevOps, data scientists, and product managers.'),('Volume Hiring','Rapid fulfillment of 50+ positions with structured screening.'),('Executive Search','C-Suite and senior leadership placement with confidentiality.'),('Campus Recruitment','Freshers drives, college partnerships, and entry-level talent pipelines.')],'steps':[('JD Analysis','Deep-dive into role requirements and team culture.'),('Sourcing','Multi-channel sourcing including proprietary talent database.'),('Screening','Technical assessments, behavioral interviews, and background verification.'),('Placement','Offer negotiation, onboarding support, and 90-day guarantee.')],'why':[('1,500+ Placed','Verified track record across IT, banking, and corporate sectors.'),('72-Hour TAT','Shortlist of 5 qualified candidates within 3 working days.'),('90-Day Guarantee','Free replacement if a candidate exits within 90 days.')],'stats':[('1500','Candidates Placed','+'),('100','Corporate Partners','+'),('72','Hour Shortlist','hrs'),('90','Day Guarantee','')]},

'Staffing': {'title':'Professional Staffing Solutions','slug':'staffing','stype':'Staffing','tagline':'Workforce Solutions','hero_title':'Flexible Workforce,','hero_highlight':'On Demand','hero_sub':'Contract, temporary, and payroll-managed staffing solutions across IT, manufacturing, retail, and services.','hero_img':'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1920&auto=format&fit=crop','accent_from':'from-teal-600','accent_to':'to-cyan-500','accent_text':'text-teal-400','accent_bg':'bg-teal-600/20','accent_border':'border-teal-500/30','icons':['Users','Clock','ShieldCheck','BarChart2'],'services':[('Contract Staffing','Short-term and project-based staff deployed within 48 hours.'),('Temp-to-Perm','Trial hires that convert to permanent on successful performance.'),('Payroll Management','Complete payroll, PF, ESI, and compliance handled by FIC.'),('Managed Services','Full outsourcing of a functional team with performance SLAs.')],'steps':[('Workforce Planning','Assess headcount gaps and skill requirements.'),('Talent Deployment','Match from active talent pool or fresh sourcing.'),('Onboarding','Documentation, induction, and compliance setup.'),('Ongoing Management','Performance tracking, attendance, and monthly reporting.')],'why':[('48-Hour Deployment','Fastest turnaround in the industry for contract staffing.'),('Compliance First','PF, ESI, TDS, and labor law compliance fully managed.'),('Scalable Teams','Add or reduce headcount based on project needs with zero friction.')],'stats':[('500','Staff Deployed','+'),('48','Hour Deployment','hrs'),('20','Client Companies','+'),('100','Compliance','%')]},

'HRSolutions': {'title':'HR Solutions & Consulting','slug':'hr-solutions','stype':'HR Solutions','tagline':'Human Resources Experts','hero_title':'People-First','hero_highlight':'HR Strategy','hero_sub':'Comprehensive HR consulting, HRMS implementation, payroll management, and HR policy design for growing businesses.','hero_img':'https://images.unsplash.com/photo-1554774853-719586f82d77?q=80&w=1920&auto=format&fit=crop','accent_from':'from-indigo-600','accent_to':'to-blue-500','accent_text':'text-indigo-400','accent_bg':'bg-indigo-600/20','accent_border':'border-indigo-500/30','icons':['Users','FileText','ShieldCheck','BarChart2'],'services':[('HRMS Implementation','Deploy and configure HR software for your team size and workflows.'),('Payroll Processing','Accurate, compliant monthly payroll with salary slips and statutory filings.'),('HR Policy Design','Handbooks, leave policies, performance frameworks, and grievance procedures.'),('HR Audit','Comprehensive review of existing HR processes and compliance gaps.')],'steps':[('HR Assessment','Evaluate current HR maturity and compliance posture.'),('Solution Design','Recommend and configure the right HR tools and policies.'),('Implementation','HRMS deployment, policy rollout, and staff communication.'),('Ongoing Support','Monthly HR advisory and compliance monitoring.')],'why':[('End-to-End HR','From recruitment policy to exit management, all under one roof.'),('Statutory Compliance','PF, ESI, Professional Tax, and Labour Law compliance guaranteed.'),('Scalable Frameworks','HR policies designed to grow with your team from 10 to 1000+.')],'stats':[('50','Companies Served','+'),('100','Compliance Rate','%'),('6','HR Modules',''),('48','Hour Policy Setup','hrs')]},

'WebDevelopment': {'title':'Corporate Web Development','slug':'web-development','stype':'Web Development','tagline':'Website Design & Development','hero_title':'Websites That','hero_highlight':'Win Business','hero_sub':'Premium corporate websites, CMS-powered platforms, and conversion-optimized landing pages that make lasting first impressions.','hero_img':'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?q=80&w=1920&auto=format&fit=crop','accent_from':'from-cyan-600','accent_to':'to-blue-500','accent_text':'text-cyan-400','accent_bg':'bg-cyan-600/20','accent_border':'border-cyan-500/30','icons':['Globe','Layers','Zap','ShieldCheck'],'services':[('Corporate Websites','Professionally designed brand websites with CMS and blog integration.'),('Landing Pages','High-converting campaign pages with A/B testing support.'),('E-commerce Websites','Custom storefronts with payment integration and inventory management.'),('Website Redesign','Modernize outdated websites with improved UX and performance.')],'steps':[('Discovery & Scope','Sitemap planning, competitor research, and design brief.'),('Design Mockups','Full-page visual designs presented for approval before coding.'),('Development','Clean, semantic code with CMS integration.'),('Launch & SEO','Deployment, domain setup, and initial on-page SEO.')],'why':[('Fast Delivery','Fully functional websites delivered in 7-21 days.'),('SEO-Ready','Every website built with search engine visibility in mind.'),('Post-Launch Support','3-month support period included with every project.')],'stats':[('150','Websites Launched','+'),('21','Day Delivery',''),('90','Lighthouse Score','avg'),('3','Month Support','')]},

'MobileApplications': {'title':'Mobile Application Solutions','slug':'mobile-applications','stype':'Mobile Applications','tagline':'Mobile-First Business Solutions','hero_title':'Business Apps','hero_highlight':'That Drive Growth','hero_sub':'Service booking apps, delivery platforms, utility applications, and customer engagement apps built for real-world usage.','hero_img':'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?q=80&w=1920&auto=format&fit=crop','accent_from':'from-purple-600','accent_to':'to-violet-500','accent_text':'text-purple-400','accent_bg':'bg-purple-600/20','accent_border':'border-purple-500/30','icons':['Smartphone','MapPin','Globe','Star'],'services':[('Service Booking Apps','On-demand service platforms with real-time booking and tracking.'),('Delivery Apps','Multi-vendor delivery platforms with driver management and live tracking.'),('Customer Loyalty Apps','Reward points, push notifications, and personalized offers.'),('Field Service Apps','Offline-capable mobile tools for field teams and technicians.')],'steps':[('App Concept','Product vision, feature list, and market validation.'),('UX Design','Interactive prototypes tested with real users.'),('Development','Agile development with bi-weekly feature releases.'),('Store Submission','App Store and Play Store listing optimization and launch.')],'why':[('Real-World Tested','Apps tested with 100+ real users before launch.'),('Offline-First','Core features work without internet connectivity.'),('Push Notifications','Targeted re-engagement campaigns built into every app.')],'stats':[('60','Apps Delivered','+'),('4.7','Avg App Rating','★'),('2','Platforms Supported',''),('30','Day Turnaround','')]},

'CloudSolutions': {'title':'Cloud Infrastructure & Solutions','slug':'cloud-solutions','stype':'Cloud Solutions','tagline':'Cloud Architecture Experts','hero_title':'Infrastructure That','hero_highlight':'Never Sleeps','hero_sub':'Scalable AWS and Azure cloud architecture, database management, auto-scaling, and zero-downtime migration services.','hero_img':'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1920&auto=format&fit=crop','accent_from':'from-blue-600','accent_to':'to-sky-500','accent_text':'text-blue-400','accent_bg':'bg-blue-600/20','accent_border':'border-blue-500/30','icons':['Cloud','Server','ShieldCheck','Zap'],'services':[('AWS Architecture','EC2, S3, RDS, Lambda, and CloudFront for production workloads.'),('Azure Deployment','Managed Kubernetes, App Services, and DevOps pipeline setup.'),('Cloud Migration','Zero-downtime lift-and-shift or full re-architecture to cloud-native.'),('Database Management','PostgreSQL, MongoDB, and Redis setup with backup and monitoring.')],'steps':[('Cloud Readiness','Evaluate existing infrastructure and migration complexity.'),('Architecture Design','VPC, security groups, IAM roles, and cost optimization plan.'),('Migration Execution','Phased migration with rollback plans and zero business disruption.'),('Monitoring & Optimization','24/7 monitoring, alerts, and monthly cost reviews.')],'why':[('AWS & Azure Certified','Certified architects with hands-on enterprise project experience.'),('Cost Optimization','Average 35% cloud cost reduction achieved for migrated clients.'),('99.9% SLA','Enterprise-grade uptime with auto-scaling and failover built in.')],'stats':[('40','Cloud Deployments','+'),('99','Uptime','%'),('35','Cost Savings','%'),('24','Monitoring','x7')]},

'APIDevelopment': {'title':'API Development & Integration','slug':'api-development','stype':'API Development','tagline':'System Integration Experts','hero_title':'Connect Every','hero_highlight':'System Seamlessly','hero_sub':'Robust REST and GraphQL APIs, third-party integrations, payment gateways, and webhook systems for connected ecosystems.','hero_img':'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1920&auto=format&fit=crop','accent_from':'from-violet-600','accent_to':'to-indigo-500','accent_text':'text-violet-400','accent_bg':'bg-violet-600/20','accent_border':'border-violet-500/30','icons':['Code','Globe','Zap','ShieldCheck'],'services':[('REST API Development','Versioned, documented APIs with authentication and rate limiting.'),('GraphQL APIs','Flexible data fetching with subscriptions for real-time applications.'),('Payment Integrations','Razorpay, Stripe, PayPal, and UPI gateway integration.'),('Third-Party Integrations','CRM, ERP, WhatsApp Business API, and marketing tool connections.')],'steps':[('Requirements Mapping','Document all systems, data flows, and integration touchpoints.'),('API Design','OpenAPI spec, authentication strategy, and error handling.'),('Development & Testing','TDD-driven API development with Postman collection documentation.'),('Deployment & Monitoring','Swagger docs, API gateway, and uptime monitoring.')],'why':[('Fully Documented','Every API delivered with interactive Swagger documentation.'),('Security First','JWT, OAuth2, API key management, and rate limiting included.'),('Webhook Expertise','Event-driven architectures with reliable retry and logging systems.')],'stats':[('200','APIs Built','+'),('99','Uptime','%'),('100','Ms Avg Response','ms'),('50','Integrations','+')]},

'BusinessAutomation': {'title':'Business Workflow Automation','slug':'business-automation','stype':'Business Automation','tagline':'Process Automation Experts','hero_title':'Eliminate Repetition,','hero_highlight':'Accelerate Growth','hero_sub':'Custom automated workflows, approval systems, report generation, and process orchestration that free your team for high-value work.','hero_img':'https://images.unsplash.com/photo-1518932945647-7a3c96943e28?q=80&w=1920&auto=format&fit=crop','accent_from':'from-amber-600','accent_to':'to-orange-500','accent_text':'text-amber-400','accent_bg':'bg-amber-600/20','accent_border':'border-amber-500/30','icons':['Settings','Zap','BarChart2','CheckCircle2'],'services':[('Workflow Automation','Replace manual tasks with trigger-based automated sequences.'),('Approval Systems','Multi-level digital approval workflows with notification and audit trail.'),('Report Automation','Scheduled data pulls, calculations, and email delivery of dashboards.'),('RPA Solutions','Robotic Process Automation for browser-based repetitive tasks.')],'steps':[('Process Audit','Map all manual workflows and quantify time/cost spent.'),('Automation Design','Design trigger-action logic and exception handling.'),('Build & Test','Develop and thoroughly test automation in staging environment.'),('Deploy & Monitor','Go-live with alert systems for failures and audit logs.')],'why':[('Immediate ROI','Most automations pay for themselves within 60 days.'),('No-Code + Custom','Leverage tools like Zapier, n8n, or custom code for complex logic.'),('Maintained & Monitored','24/7 monitoring of all automations with instant failure alerts.')],'stats':[('80','Workflows Automated','+'),('60','ROI Payback','days'),('90','Manual Work Eliminated','%'),('100','Automation Monitoring','%')]},
}

template = """import React from 'react';
import {{ {imports} }} from 'lucide-react';
import ServicePageTemplate from '../../components/templates/ServicePageTemplate';

const {name} = () => (
  <ServicePageTemplate
    title="{title}"
    description="{hero_sub}"
    tagline="{tagline}"
    heroTitle="{hero_title}"
    heroHighlight="{hero_highlight}"
    heroSubtitle="{hero_sub}"
    heroImage="{hero_img}"
    accentFrom="{accent_from}"
    accentTo="{accent_to}"
    accentText="{accent_text}"
    accentBg="{accent_bg}"
    accentBorder="{accent_border}"
    stats={{[{stats}]}}
    servicesTitle="{stype} Services"
    services={{[{services_jsx}]}}
    processTitle="Our Delivery Process"
    processSteps={{[{steps_jsx}]}}
    whyTitle="Why FIC for {stype}?"
    whyPoints={{[{why_jsx}]}}
    serviceType="{stype}"
    serviceSlug="{slug}"
    formTitle="Start Your {stype} Project"
    formBullets={{['Free initial consultation', 'Detailed proposal within 48 hours', 'No long-term lock-in contracts']}}
  />
);

export default {name};
"""

for name, p in pages.items():
    icons = p['icons']
    icon_import_str = ', '.join(icons)
    
    stats = ', '.join(
        '{{ value: "{}", label: "{}", suffix: "{}" }}'.format(s[0], s[1], s[2])
        for s in p['stats']
    )
    services = ', '.join(
        '{{ icon: {}, title: "{}", desc: "{}" }}'.format(icons[i % len(icons)], sv[0], sv[1])
        for i, sv in enumerate(p['services'])
    )
    steps = ', '.join(
        '{{ title: "{}", desc: "{}" }}'.format(s[0], s[1])
        for s in p['steps']
    )
    why = ', '.join(
        '{{ title: "{}", desc: "{}" }}'.format(w[0], w[1])
        for w in p['why']
    )
    
    code = template.format(
        name=name,
        imports=icon_import_str,
        title=p['title'],
        tagline=p['tagline'],
        hero_title=p['hero_title'],
        hero_highlight=p['hero_highlight'],
        hero_sub=p['hero_sub'],
        hero_img=p['hero_img'],
        accent_from=p['accent_from'],
        accent_to=p['accent_to'],
        accent_text=p['accent_text'],
        accent_bg=p['accent_bg'],
        accent_border=p['accent_border'],
        stype=p['stype'],
        slug=p['slug'],
        stats=stats,
        services_jsx=services,
        steps_jsx=steps,
        why_jsx=why,
    )
    
    with open(os.path.join(base, f'{name}.jsx'), 'w', encoding='utf-8') as f:
        f.write(code)

print(f'OK: {len(pages)} pages written.')
